cities = {
    beijing: ["北京",  12],
    shanghai: ["上海", 13],
    guangzhou: ["广州",  13],
    shenzhen: ["深圳",  13],
    chengdu: ["成都",  12],
    hongkong: ["香港",  13],
    wuhan: ["武汉",  13],
    hangzhou: ["杭州", 14],
    chongqing: ["重庆", 14],
    zhengzhou: ["郑州", 14],
    nanjing: ["南京", 14],
    xian: ["西安", 14],
    suzhou: ["苏州", 14],
    tianjin: ["天津", 14],
    changsha: ["长沙", 15],
    fuzhou: ["福州", 15],
};